language: python
sudo: required # For overwriting /etc/hosts, to test hostname based routing.

python:
- 2.7
- 3.6
env:
  matrix:
    - DJANGO_VERSION='1.8.19'  # LTS
    - DJANGO_VERSION='1.11.11'  # LTS
    - DJANGO_VERSION='2.0.3'  # not LTS
matrix:
  fast_finish: true
  exclude:
    - env: DJANGO_VERSION='2.0.3'
      python: 2.7  # only python3

install:
- pip install -r requirements-dev.txt
# Load pinned versions first, and get dependencies for setup.py
- pip install -r requirements.txt

before_script:
- set -o errexit
- pip install django==$DJANGO_VERSION
- sudo sh -c 'echo "127.0.0.1 container-name.docker.localhost" >> /etc/hosts'
script: ./test.sh
deploy:
  # Defaults to only deploy on master;
  # PyPi blocks the same version from being uploaded twice.
  provider: pypi
  distributions: sdist bdist_wheel
  user: scottx611x
  password:
    secure: "ZoPiPFa9ta67+w3wxGm47e8SKZiwWb41DfBHUhSiYyDoyEjgryiMX5OohljgwCNlIvLTBKkpze5HtCxEXrpfgjB1to6zWORmsMmm71dse+Xg812sh9We6KWLOgpNn39nOly6zGAbAeedWZqfUvv5WBTsY5Pz0OruD1GSKw8oagKPvHJQy8nfZzrRa+m5sRrHYB0lMCRRd8EpercfBCkaKAAVICclySXnPxmA+Tml8ZmfgUk+ICwlwDOnWQaaCh4tjmG9C65gro2MY2Af7RkwQVoeeSfdTc8Y7Dq6JQ0e/KVAVsKg98Lrbn2ZHnEKeLh64FoWGRRKlKociA8KxOS3aitjySWFrbHKuFxIJ3RDrxI/TVWScER7ZCaxu/P/+T2PZxOcjFn1tkijdKF8co5tgYznDkwRG7WTipCeGfAjZLeFWfCHs0dOUAAi46JfevmpTulwMbzYZ27r1lLy/GHbtxwFeo+19JO8pycBHlb8PhQSTb7x7FNmKbk3kyCk4iKE6JGGrKRiwQlOynptn6BcxIy3WYWcbZ6nkG16OVwTKggUisCu/TBWIiQE0US7mnwVAwKAhhiaYD4R6s3IO9dHiXFdY1Vsk5NyO4kK/kmOkaIOexHLxICreiDeyAdcBrr0z8CGxb/BozSQA+2ExRStl5xLcPyTXSN7YuHS0VYgqFs="
  on:
    branch: master
    python: 3.6
    condition: $DJANGO_VERSION = '1.11.11'
